### ISSUE TITLE
Terminate in an usual way

### ISSUE THREAD

**Issue by davidrahusen** [stackforce/serial-interface-cli#2]
When launching the Serial CLI the usual way (`startcli.cmd`), it opens up a windows command line window, prints the help text and returns to prompt.

When launching `sfserialcli.exe` manually, I get the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Illegal cast to string; type is actually empty

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
Afterwards `sfserialcli.exe` dies.

Any ideas?

**Comment by davidrahusen** [comment]
Forgot to mention, this was done on a Win 10 64bit. ;-)

**Comment by mrpelotazo** [comment]
It seems to come from the parameter handling when no parameter is specified. Please invoke the program specifying at least a serial port as parameter.
A proper handling for the no-paramter case is in progress.
